
const productList = [
  {
    id: 'pro01',
    src: './image/product_list_01.jpg',
    name: 'soft love bunny (bumper) 아이폰케이스',
    price: '17,000',
    color: ['blue', 'multi'],
    review: 32,
    sell: 100,
    update: '2025-01-03',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro02',
    src: './image/product_list_02.jpg',
    name: 'dote pattern epoxy case (4 colors) 아이폰 갤럭시 케이스',
    price: '21,000',
    color: ['black'],
    review: 3,
    sell: 59,
    update: '2025-02-05',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro03',
    src: './image/product_list_03.jpg',
    name: '[+맥세이프]snow blossom epoxy case',
    price: '22,000',
    color: ['white', 'multi'],
    review: 8,
    sell: 80,
    update: '2025-02-03',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro04',
    src: './image/product_list_04.jpg',
    name: 'BEBE FLOWER CASE [WHITE]',
    price: '29,000',
    color: ['white'],
    review: 1,
    sell: 35,
    update: '2025-03-19',
    brand: 'iphone',
    device: ['all'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro05',
    src: './image/product_list_05.jpg',
    name: 'Clover case (JellyJell hard)',
    price: '19,000',
    color: ['multi'],
    review: 2,
    sell: 49,
    update: '2025-05-03',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro06',
    src: './image/product_list_06.jpg',
    name: 'Ribbon Breeze Phone case (에폭시 범퍼)',
    price: '22,000',
    color: ['white', 'blue', 'multi'],
    review: 43,
    sell: 109,
    update: '2025-04-01',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver'],
    soldout: 'no'
  },
  {
    id: 'pro07',
    src: './image/product_list_07.jpg',
    name: 'mew고양이 에폭시 범퍼케이스',
    price: '25,000',
    color: ['white'],
    review: 9,
    sell: 201,
    update: '2025-06-23',
    brand: 'iphone',
    device: ['all'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro08',
    src: './image/product_list_08.jpg',
    name: 'Strawberry_(begie) Phone case (에폭시 범퍼)',
    price: '22,000',
    color: ['gray'],
    review: 20,
    sell: 150,
    update: '2025-04-17',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro09',
    src: './image/product_list_09.jpg',
    name: 'Different Shaped Hearts Phone Case',
    price: '26,000',
    color: ['red'],
    review: 5,
    sell: 30,
    update: '2025-01-15',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro10',
    src: './image/product_list_10.jpg',
    name: '[16e출시][+맥세이프][+갤럭시]twinkle star epoxy case',
    price: '22,000',
    color: ['white', 'multi'],
    review: 8,
    sell: 73,
    update: '2025-05-28',
    brand: 'iphone',
    device: ['all'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro11',
    src: './image/product_list_11.jpg',
    name: 'Pink snoopy epoxy case_HC249DEP002O',
    price: '39,000',
    color: ['pink'],
    review: 13,
    sell: 80,
    update: '2025-01-02',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro12',
    src: './image/product_list_12.jpg',
    name: 'kaki line 에폭시범퍼케이스',
    price: '21,000',
    color: ['green', 'orange', 'multi'],
    review: 21,
    sell: 98,
    update: '2025-04-07',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro13',
    src: './image/product_list_13.jpg',
    name: 'eucalyptus epoxy case',
    price: '22,000',
    color: ['green'],
    review: 72,
    sell: 240,
    update: '2025-02-11',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver'],
    soldout: 'no'
  },
  {
    id: 'pro14',
    src: './image/product_list_14.jpg',
    name: '[레진] Butterfly World 폰케이스',
    price: '38,000',
    color: ['multi', 'white'],
    review: 38,
    sell: 60,
    update: '2025-03-03',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro15',
    src: './image/product_list_15.jpg',
    name: '_starfish (bumper) 휴대폰케이스',
    price: '20,000',
    color: ['blue', 'multi'],
    review: 21,
    sell: 42,
    update: '2025-04-28',
    device: [],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro16',
    src: './image/product_list_16.jpg',
    name: '아이 원트 고 홈 화이트 투명 케이스',
    price: '18,000',
    color: ['white', 'multi'],
    review: 98,
    sell: 203,
    update: '2025-02-28',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver'],
    soldout: 'no'
  },
  {
    id: 'pro17',
    src: './image/product_list_17.jpg',
    name: '[SET] 블랑 튀튀 플라워톡 세트 (슬림카드범퍼맥세이프)',
    price: '34,000',
    color: ['white'],
    review: 20,
    sell: 50,
    update: '2025-03-31',
    brand: 'iphone',
    device: ['all'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro18',
    src: './image/product_list_18.jpg',
    name: 'Afternoon Leaf',
    price: '21,000',
    color: ['green'],
    review: 19,
    sell: 49,
    update: '2025-04-01',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro19',
    src: './image/product_list_19.jpg',
    name: '스카이블루 무뚝뚝꽃',
    price: '21,000',
    color: ['black', 'multi'],
    review: 3,
    sell: 10,
    update: '2025-04-13',
    brand: 'iphone',
    device: ['all'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro20',
    src: './image/product_list_20.jpg',
    name: 'taste sweet 디자인 [카드수납 폰케이스]',
    price: '17,000',
    color: ['red'],
    review: 35,
    sell: 80,
    update: '2025-02-05',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro21',
    src: './image/product_list_21.jpg',
    name: '올리야 치칸추크 작가, Apples 01 맥세이프 케이스',
    price: '24,900',
    color: ['yellow', 'blue', 'multi'],
    review: 15,
    sell: 40,
    update: '2025-06-13',
    brand: 'iphone',
    device: ['all'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro22',
    src: './image/product_list_22.jpg',
    name: 'Black silver Soap phone case',
    price: '21,000',
    color: ['black'],
    review: 11,
    sell: 30,
    update: '2025-07-03',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver'],
    soldout: 'no'
  },
  {
    id: 'pro23',
    src: './image/product_list_23.jpg',
    name: '[하드/카드수납 폰케이스] 더스트 플래닛',
    price: '22,000',
    color: ['orange', 'red', 'multi'],
    review: 3,
    sell: 12,
    update: '2025-07-17',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro24',
    src: './image/product_list_24.jpg',
    name: '(실버 에폭시) 스프링 썸머 collage 에폭시 아이폰 갤럭시 케이스',
    price: '30,000',
    color: ['pink', 'multi'],
    review: 9,
    sell: 60,
    update: '2025-07-12',
    brand: 'iphone',
    device: ['all'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro25',
    src: './image/product_list_25.jpg',
    name: '[+맥세이프][+갤럭시]메론 하트 에폭시 케이스',
    price: '22,000',
    color: ['green', 'pink', 'multi'],
    review: 7,
    sell: 20,
    update: '2025-05-03',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro26',
    src: './image/product_list_26.jpg',
    name: '[SET] 오션팝 반투명 케이스+조약돌톡',
    price: '21,700',
    color: ['white', 'multi'],
    review: 10,
    sell: 37,
    update: '2025-02-03',
    brand: 'iphone',
    device: ['all'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro27',
    src: './image/product_list_27.jpg',
    name: '딸기! 범퍼 케이스 (white)',
    price: '24,000',
    color: ['red', 'white', 'multi'],
    review: 40,
    sell: 102,
    update: '2025-07-13',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro28',
    src: './image/product_list_28.jpg',
    name: '애플 쥬스 phone case(hard)',
    price: '22,000',
    color: ['green'],
    review: 3,
    sell: 11,
    update: '2025-07-15',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver', 'eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro29',
    src: './image/product_list_29.jpg',
    name: '뒹굴 tok & case set (맥세이프 케이스 세트)',
    price: '36,000',
    color: ['white', 'pink'],
    review: 9,
    sell: 36,
    update: '2025-06-08',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro30',
    src: './image/product_list_30.jpg',
    name: 'Lets make a star 글라스 범퍼 케이스 pink',
    price: '20,500',
    color: ['white', 'pink'],
    review: 7,
    sell: 20,
    update: '2025-06-16',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver'],
    soldout: 'no'
  },
  {
    id: 'pro31',
    src: './image/product_list_31.jpg',
    name: '별꽃놀이 젤리 하드 케이스 민트',
    price: '18,000',
    color: ['white', 'mint', 'multi'],
    review: 18,
    sell: 42,
    update: '2025-03-04',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro32',
    src: './image/product_list_32.jpg',
    name: '맥세이프 케이스 : 오이 (real)',
    price: '19,000',
    color: ['green'],
    review: 13,
    sell: 69,
    update: '2025-05-07',
    brand: 'iphone',
    device: ['all'],
    event: ['eventNow'],
    soldout: 'no'
  },
  {
    id: 'pro33',
    src: './image/product_list_33.jpg',
    name: 'cheese cat case',
    price: '23,000',
    color: ['yellow', 'orange', 'multi'],
    review: 63,
    sell: 238,
    update: '2025-07-15',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro34',
    src: './image/product_list_34.jpg',
    name: 'NTA Silverborn Stellaris Bumper Mirror Phone Case',
    price: '26,000',
    color: ['black', 'gray'],
    review: 1,
    sell: 5,
    update: '2025-07-03',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: [],
    soldout: 'no'
  },
  {
    id: 'pro35',
    src: './image/product_list_35.jpg',
    name: '포슬 드로잉 빈티지 단추 케이스 더스트 블루',
    price: '29,000',
    color: ['blue', 'multi'],
    review: 30,
    sell: 140,
    update: '2025-07-16',
    brand: 'iphone',
    device: ['16', '16Pro', '16ProMax', '16Plus', '16e', '15', '15Pro', '15ProMax', '15Plus'],
    event: ['freeDeliver'],
    soldout: 'no'
  },
  {
    id: 'pro36',
    src: './image/product_list_36.jpg',
    name: '워크북 글래스 범퍼 케이스',
    price: '20,000',
    color: ['white', 'multi'],
    review: 2,
    sell: 36,
    update: '2025-07-01',
    brand: 'iphone',
    device: ['all'],
    event: ['freeDeliver'],
    soldout: 'no'
  },


]

export default productList;